from .auth_views import *
from .dashboard_views import *
from .location_views import *
from .water_views import *
from .quality_views import *
from .gis_views import *
from .balance_views import *
from .ml_views import *
from .dataset_views import *
from .upload_dashboard import *
from .well_views import *
from .tool_views import *