from django.urls import path
from .views import (
    dashboard,
    open_qgis,
    wells,
    waterlevel,
    pumping,
    watertable,
    tds,
    salinity,
    well_detail,
    add_water_level,
    add_pumping,
    add_rainfall,
    add_weather,
    add_watertable,
    add_tds,
    add_salinity,
    village_clusters_geojson,
    upload_gis_file,
    run_gempy,
    run_modflow_view,
    water_balance_prediction,
    login_user,
    register,
    add_water_balance,
    upload_dataset,
    retrain_lstm,
    ai_dashboard,
    forecast_api,
    water_balance_history,
    add_location,
    list_gis_layers,
    location_list,
    delete_location,
    resource_folders,
    resource_folder_detail,
    resource_upload_files,
    resource_file_detail,
    parameter_list,       
    parameter_delete,
    stale_locations,
    retrain_all_stale,
    list_wells,
    add_well,
    update_well,
    delete_well,
    export_wells,
    list_tool_cards,
    add_tool_card,
    edit_tool_card,
    delete_tool_card,
    add_tool_card_image,
    delete_tool_card_image,
    verify_admin_password,
    list_gis_files,
    download_gis_file,
    delete_gis_file,
    gis_geojson,
    get_dashboard_banner,
    upload_dashboard_banner,
    delete_dashboard_banner,

)

urlpatterns = [
    path("auth/login/", login_user),
    path("dashboard/", dashboard),
    path("wells/", list_wells),
    path("wells/<int:well_id>/", well_detail),
    path("waterlevel/", waterlevel),
    path("pumping/", pumping),
    path("watertable/", watertable),
    path("tds/", tds),
    path("salinity/", salinity),
    path("open-qgis/", open_qgis),
    path("water-level/add/", add_water_level),
    path("pumping/add/", add_pumping),
    path("rainfall/add/", add_rainfall),
    path("weather/add/", add_weather),
    path("watertable/add/", add_watertable),
    path("tds/add/", add_tds),
    path("salinity/add/", add_salinity),
    path("village-clusters/", village_clusters_geojson),
    path("gis/upload/", upload_gis_file),
    path("gis/layers/", list_gis_layers),
    path("run-gempy/", run_gempy),
    path("run-modflow/", run_modflow_view),
    path("ml/predict/", water_balance_prediction),
    path("auth/register/", register),
    path("water-balance/add/", add_water_balance),
    path("ml/upload-dataset/", upload_dataset),
    path("ml/retrain/", retrain_lstm),
    path("ml/dashboard/",ai_dashboard,name="ai-dashboard",),
    path("ml/forecast/<str:period>/",forecast_api,),
    path("water-balance/history/",water_balance_history),
    path("locations/", location_list),
    path("location-list/", location_list),
path(
    "location/add/",
    add_location,
    name="add_location",
),
path(
    "location/<int:id>/",
    delete_location,
    name="delete_location"
),
    path("resources/folders/", resource_folders),
    path("resources/folders/<int:folder_id>/", resource_folder_detail),
    path("resources/folders/<int:folder_id>/upload/", resource_upload_files),
    path("resources/files/<int:file_id>/", resource_file_detail),
    path("parameters/", parameter_list),
    path("parameters/<int:id>/", parameter_delete),
    path("ml/stale-locations/", stale_locations),
    path("ml/retrain-all-stale/", retrain_all_stale),
    path("well/add/", add_well),
    path("well/<int:pk>/edit/", update_well),
    path("well/<int:pk>/", delete_well),
    path("well/export/", export_wells),
    path("tools/", list_tool_cards),
    path("tools/add/", add_tool_card),
    path("tools/<int:id>/edit/", edit_tool_card),
    path("tools/<int:id>/delete/", delete_tool_card),
    path("tools/<int:id>/images/add/", add_tool_card_image),
    path("tools/images/<int:image_id>/delete/", delete_tool_card_image),
    path("verify-admin-password/", verify_admin_password),
    path("gis/files/", list_gis_files),
    path("gis/files/<int:id>/download/", download_gis_file),
    path("gis/files/<int:id>/", delete_gis_file),
    path("gis/geojson/", gis_geojson),
    path("dashboard/banner/", get_dashboard_banner),
    path("dashboard/banner/upload/", upload_dashboard_banner),
    path("dashboard/banner/delete/<int:image_id>/", delete_dashboard_banner),
]