from django.urls import path
from .views import (
    dashboard,
    open_qgis,
    wells,
    waterlevel,
    pumping,
    watertable,
    tds,
    salinity,
    well_detail,
    add_water_level,
    add_pumping,
    add_rainfall,
    add_weather,
    add_watertable,
    add_tds,
    add_salinity,
    village_clusters_geojson,
    upload_gis_file,
    run_gempy,
    run_modflow_view,
    groundwater_prediction,
    register_user,
    login_user,
)

urlpatterns = [
    path("auth/register/", register_user),
    path("auth/login/", login_user),
    path("dashboard/", dashboard),
    path("wells/", wells),
    path("wells/<int:well_id>/", well_detail),
    path("waterlevel/", waterlevel),
    path("pumping/", pumping),
    path("watertable/", watertable),
    path("tds/", tds),
    path("salinity/", salinity),
    path("open-qgis/", open_qgis),
    path("water-level/add/", add_water_level),
    path("pumping/add/", add_pumping),
    path("rainfall/add/", add_rainfall),
    path("weather/add/", add_weather),
    path("watertable/add/", add_watertable),
    path("tds/add/", add_tds),
    path("salinity/add/", add_salinity),
    path("village-clusters/", village_clusters_geojson),
    path("gis/upload/", upload_gis_file),
    path("run-gempy/", run_gempy),
    path("run-modflow/", run_modflow_view),
    path("predict/", groundwater_prediction),
]