# Generated by Django 5.2.15 on 2026-07-26 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundwater', '0012_resourcefolder_resourcefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('inflow', 'Inflow'), ('outflow', 'Outflow')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='waterbalance',
            name='values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='MLModelState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs_retrain', models.BooleanField(default=True)),
                ('last_retrained_at', models.DateTimeField(blank=True, null=True)),
                ('active_parameter_signature', models.CharField(blank=True, default='', max_length=64)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ml_state', to='groundwater.location')),
            ],
        ),
    ]
