# Generated by Django 5.2.15 on 2026-07-26 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groundwater', '0014_migrate_water_balance_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterbalance',
            name='Dp',
        ),
        migrations.RemoveField(
            model_name='waterbalance',
            name='Et',
        ),
        migrations.RemoveField(
            model_name='waterbalance',
            name='I',
        ),
        migrations.RemoveField(
            model_name='waterbalance',
            name='O',
        ),
        migrations.RemoveField(
            model_name='waterbalance',
            name='Re',
        ),
        migrations.RemoveField(
            model_name='waterbalance',
            name='Ri',
        ),
        migrations.RemoveField(
            model_name='waterbalance',
            name='Rr',
        ),
        migrations.RemoveField(
            model_name='waterbalance',
            name='Se',
        ),
        migrations.RemoveField(
            model_name='waterbalance',
            name='Si',
        ),
    ]
