# Generated by Django 5.2.15 on 2026-07-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundwater', '0015_remove_waterbalance_dp_remove_waterbalance_et_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbalance',
            name='entry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
