# Generated by Django 5.2.15 on 2026-07-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundwater', '0017_backfill_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbalance',
            name='entry_date',
            field=models.DateField(),
        ),
    ]
