# Generated by Django 5.2.15 on 2026-07-27 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundwater', '0018_alter_waterbalance_entry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_id', models.CharField(max_length=100)),
                ('observation_date', models.DateField()),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='groundwater.location')),
            ],
            options={
                'ordering': ['-observation_date'],
            },
        ),
        migrations.CreateModel(
            name='WellParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=150)),
                ('parameter_value', models.CharField(max_length=100)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='groundwater.well')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
