# Generated by Django 5.2.15 on 2026-07-27 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundwater', '0019_well_wellparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon_name', models.CharField(blank=True, max_length=50, null=True)),
                ('path', models.CharField(blank=True, max_length=200, null=True)),
                ('action_label', models.CharField(blank=True, max_length=100, null=True)),
                ('is_core', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='wellparameter',
            name='parameter_name',
        ),
        migrations.AddField(
            model_name='wellparameter',
            name='parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='well_parameters', to='groundwater.parameter'),
        ),
        migrations.CreateModel(
            name='ToolCardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tool_card_images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('tool_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='groundwater.toolcard')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
