# Generated by Django 5.2.15 on 2026-07-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundwater', '0020_toolcard_remove_wellparameter_parameter_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellparameter',
            name='parameter',
        ),
        migrations.AddField(
            model_name='wellparameter',
            name='parameter_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
