# Generated by Django 5.2.15 on 2026-07-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundwater', '0021_remove_wellparameter_parameter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gislayers',
            name='file_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gislayers',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gislayers',
            name='original_filename',
            field=models.TextField(blank=True, null=True),
        ),
    ]
